// Generated by CoffeeScript 1.7.1
// (function() {
//   $(function() {
//     return $('video.fullscreen').bind("ended", function() {
//       return console.log("I'm done");
//     });
//   });
//
// }).call(this);

(function() {
  var emailIsValid, setupEmailModal;

  setupEmailModal = function() {
    // Parse.initialize("PJrCjZ1mqVIqBhYwdv2DxMZj8kAqAntfMaYozqRY", "sUQonoF8Y2O3YFtuweJ8V0uaPwS4sbDKsSAtQK9R");
    $('#email-modal').on('click', function(e) {
      return $(this).fadeOut();
    });
    $('.join-beta').on('click', function(e) {
      e.preventDefault();
      return $('#email-modal').fadeIn();
    });
    $('input').on('click', function(e) {
      return e.stopImmediatePropagation();
    });
    $('button').on('click', function(e) {
      return e.stopImmediatePropagation();
    });
    return $('.email-form').submit(function(e) {
      var Contact, action, checkmark, contact, email, errorField, form, formData, join, spinner, successField;
      e.preventDefault();
      form = $(this);
      action = form.attr('action');
      email = $.trim(form.find('input[name=email]')[0].value);
      successField = $(form.find('.form-message'));
      errorField = $(form.find('.form-error'));
      spinner = $(form.find('.loader'));
      join = $(form.find('.join'));
      checkmark = $(form.find('.done'));
      successField.html('').fadeOut(0);
      errorField.html('').fadeOut(0);
      if (emailIsValid(email)) {
        join.hide();
        checkmark.hide();
        spinner.fadeIn();
        formData = {
          'email': email
        };
        Contact = Parse.Object.extend("Contact");
        contact = new Contact();
        return contact.save({
          email: email
        }).then(function(object) {
          successField.html('Thank you. You will receive an email soon.').fadeIn();
          spinner.hide();
          return checkmark.fadeIn();
        });
      } else {
        return errorField.html('Please check your email again. Thanks.').fadeIn();
      }
    });
  };

  emailIsValid = function(email) {
    var emailReg;
    emailReg = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
    return emailReg.test(email);
  };

  $(function() {
    setupEmailModal();
  });

}).call(this);
